# Generated by Django 4.2.3 on 2023-07-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createday', models.DateField()),
                ('coment', models.CharField(max_length=200)),
            ],
        ),
    ]
