# Generated by Django 4.2.3 on 2023-07-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sako', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
